### ISSUE TITLE
Support exposing the currently rendered `itemsPerRow`

### ISSUE THREAD

**Issue by lincolnthree** [lVlyke/lithium-ngx-virtual-scroll#16]
It is sometimes useful to understand how many items per row are currently being rendered, outside of the component itself. Something like this:

virtual-scroll.component.ts: line 291
```
// The bounds of the scroll container, in pixels
const renderedBounds: VirtualScroll.Rect = {
   left: scrollPosition.x,
   top: scrollPosition.y,
   right: scrollPosition.x + scrollContainer!.clientWidth,
   bottom: scrollPosition.y + scrollContainer!.clientHeight
};
 const bufferLengthPx = (scrollContainer!.clientHeight) * bufferLength;

// Calculate the number of rendered items per row
   this.itemsPerRow = gridList ? Math.floor(scrollContainer!.clientWidth / itemWidth!) : 1; // <-- just set this on the component instance and expose it?
   const virtualScrollHeight = items.length * itemHeight! / this.itemsPerRow;

// Adjust the bounds by the buffer length and clamp to the edges of the container
```

page.html
```
<li-virtual-scroll #scroll></li-virtual-scroll>
```

page.ts
```
  @ViewChild(VirtualScroll<Card>, { static: false }) scroll: VirtualScroll<Card>;

...

someFunction() {
   const rowLength = this.scroll.itemsPerRow ?? 1;
   ...
}
```

**Comment by lincolnthree** [comment]
Or, possibly create a method to call to get the current item specs:

```
const { itemHeight, itemWidth, itemsPerRow } = this.scroll.getItemDimensions()
```

**Comment by lincolnthree** [comment]
PS. This is quite possibly the best multi-column virtual scroll library I have EVER tested, and I've been looking for a replacement for `ngx-virtual-scroll` for a LONG time. I'm super impressed by this, and the way you've created a thin-wrapper for responsive components that presents a very fluent design using annotations and simple APIs. I haven't grokked all of it yet, but so far ... very nicely done.

**Comment by Sampath-Lokuge** [comment]
Have you used this with `Angular 15+`?

**Comment by Sampath-Lokuge** [comment]
Ok sure, thanks a lot!

**Comment by lVlyke** [comment]
@lincolnthree Makes sense! `itemsPerRow` is now exposed as a public property in the upcoming [0.3.0](https://github.com/lVlyke/lithium-ngx-virtual-scroll/commit/09185a07488dc836fc1dc58be8001b7fc640f79e#diff-7ff6ef5039db7b703e0402022e2a0a3f8ad97ec8321a917b76fede2198d1daa0) version.

**Comment by lVlyke** [comment]
@lincolnthree Really appreciate the feedback! I made the library largely out of frustration of being unable to find a satisfactory multi-column virtual scroll implementation. Glad to see others are finding it useful!
