### ISSUE TITLE
Is this support for Angular 15+?

### ISSUE THREAD

**Issue by Sampath-Lokuge** [lVlyke/lithium-ngx-virtual-scroll#18]
Hi,

Is this support for Angular 15+? Thanks!

**Comment by lincolnthree** [comment]
It works with Angular 15 if you modify the dependency version ranges for Angular in package.json, otherwise NPM will give you conflicts. But there's nothing incompatible about the code itself.

**Comment by Sampath-Lokuge** [comment]
>  if you modify the dependency version ranges for Angular in package.json,

Sorry, I didn't get this. Will it not work?

> npm install @lithiumjs/angular @lithiumjs/ngx-virtual-scroll

**Comment by lincolnthree** [comment]
Try it?

**Comment by Sampath-Lokuge** [comment]
Not yet. I have done some research before starting the implementation hence no multi-column support from the Angular official scroller. So I'll let you know once I'll get any issues here. Thanks!

**Comment by lVlyke** [comment]
Version 0.2.3 has just been released with support for Angular 15.

**Comment by Sampath-Lokuge** [comment]
Great. Thanks!
