### ISSUE TITLE
No public method to set scroll position

### ISSUE THREAD

**Issue by ghenry22** [lVlyke/lithium-ngx-virtual-scroll#24]
The scrollPosition Value is read-only currently.

This means we cannot implement something like a simple scroll to top functionality.

Proposed Solution
Implement a "ScrollTo" function which can accept an item number in the virtual list.
Implement a "ScrollToXY" function which can accept x/y co-ordinates to set the scrollPosition directly ie scrollToXY({x: 0, y: 0})

**Comment by lVlyke** [comment]
The component responds to native HTML scroll events, so to update the scroll position you can simply scroll the container element itself. For example:

```ts
//MyComponent.ts:
import { ElementRef } from ‘@angular/core’;

class MyComponent {

    @ViewChild("virtualScroll", { read: ElementRef })
    public scrollContainer: ElementRef<HTMLElement>;

    …

    public scrollTo(yPos: number) {
        // li-virtual-scroll will automatically re-render based on the new scroll position
        this.scrollContainer.nativeElement.scrollTo(0, yPos);
    }
}
```

```html
<!-- MyComponent.html -->
<li-virtual-scroll #virtualScroll [items]="items">
	…
</li-virtual-scroll>
```

**Comment by ghenry22** [comment]
Got it, will give that a try thanks!
